#!/bin/bash

function exportwithoutlayer()
{
    xmlstarlet c14n $1 | sed  >tmp.svg  -e "s/g id=\"layer\\($2\\)\" style=\"display:inline\"/g id=\"layer\\1\" style=\"display:none\"/"
    inkscape tmp.svg -D -d 300 --export-png=$3
    rm tmp.svg
}

function exportwithlayer()
{
    xmlstarlet c14n $1 | sed  -e "s/g id=\"layer\\([0-9]*\\)\" style=\"display:inline\"/g id=\"layer\\1\" style=\"display:none\"/" | sed > tmp.svg -e "s/g id=\"layer\\($2\\)\" style=\"display:none\"/g id=\"layer\\1\" style=\"display:inline\"/"
    inkscape tmp.svg -D -d 300 --export-png=$3
    #rm tmp.svg
}

# Migration
INPUT=migration-pv.svg
exportwithoutlayer $INPUT "[234]" migration-pv1.png
exportwithoutlayer $INPUT "[34]" migration-pv2.png
exportwithoutlayer $INPUT "[4]" migration-pv3.png
inkscape $INPUT -i layer1 -d 300 --export-png=migration-pv4.png

# Migration with PVC first
INPUT=migration-pvc.svg
exportwithoutlayer $INPUT "[2345]" migration-pvc1.png
exportwithoutlayer $INPUT "[345]" migration-pvc2.png
exportwithoutlayer $INPUT "[45]" migration-pvc3.png
exportwithoutlayer $INPUT "[5]" migration-pvc4.png
exportwithoutlayer $INPUT "999" migration-pvc5.png
